### PR TITLE
Release 0.0.116

### PR DESCRIPTION
**Pull request by tnull**

### CODE REVIEW

**Comment by tnull** [comment]
Should be good to go now that https://github.com/lightningdevkit/ldk-c-bindings/pull/110 landed.

**Comment by tnull** [comment]
Included minor fixes:
```diff
diff --git a/ci/LDKSwift/Sources/LDKSwift/batteries/ChannelManagerConstructor.swift b/ci/LDKSwift/Sources/LDKSwift/batteries/ChannelManagerConstructor.swift
index 32c7bcfe..224b6e36 100644
--- a/ci/LDKSwift/Sources/LDKSwift/batteries/ChannelManagerConstructor.swift
+++ b/ci/LDKSwift/Sources/LDKSwift/batteries/ChannelManagerConstructor.swift
@@ -47,5 +47,5 @@ public struct ChannelManagerConstructionParameters {
     public var logger: Logger
     
-    public init (config: UserConfig, entropySource: EntropySource, nodeSigner: NodeSigner, signerProvider: SignerProvider, feeEstimator: FeeEstimator, chainMonitor: ChainMonitor, txBroadcaster: BroadcasterInterface, logger: Logger, enableP2PGossip: Bool = false, scorer: MultiThreadedLockableScore? = nil, scoreParams: ProbabilisticScoringFeeParameters? = ProbabilisticScoringFeeParameters.initWithDefault(), payerRetries: Retry = Retry.initWithAttempts(a: UInt(3))) {
+    public init (config: UserConfig, entropySource: EntropySource, nodeSigner: NodeSigner, signerProvider: SignerProvider, feeEstimator: FeeEstimator, chainMonitor: ChainMonitor, txBroadcaster: BroadcasterInterface, logger: Logger, enableP2PGossip: Bool = false, scorer: MultiThreadedLockableScore? = nil, scoreParams: ProbabilisticScoringFeeParameters? = nil, payerRetries: Retry = Retry.initWithAttempts(a: UInt(3))) {
         self.config = config
         self.entropySource = entropySource
@@ -59,5 +59,9 @@ public struct ChannelManagerConstructionParameters {
         self.enableP2PGossip = enableP2PGossip
         self.scorer = scorer
-        self.scoreParams = scoreParams
+        if scorer != nil && scoreParams == nil {
+            self.scoreParams = ProbabilisticScoringFeeParameters.initWithDefault()
+        } else {
+            self.scoreParams = scoreParams
+        }
         self.payerRetries = payerRetries
     }
@@ -183,12 +187,15 @@ public class ChannelManagerConstructor: NativeTypeWrapper {
 
 
-        let noCustomMessages = IgnoringMessageHandler()
+        let noCustomMessages = IgnoringMessageHandler().asCustomMessageHandler()
+        let noOnionMessages = IgnoringMessageHandler().asOnionMessageHandler()
+        let noRoutingMessages = IgnoringMessageHandler().asRoutingMessageHandler()
+
         var messageHandler: MessageHandler!
         if let netGraph = self.netGraph, params.enableP2PGossip {
             let p2pGossipSync = P2PGossipSync(networkGraph: netGraph, utxoLookup: nil, logger: params.logger)
             self.graphMessageHandler = GossipSync.initWithP2P(a: p2pGossipSync)
-            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: p2pGossipSync.asRoutingMessageHandler(), onionMessageHandlerArg: noCustomMessages.asOnionMessageHandler(), customMessageHandlerArg: noCustomMessages.asCustomMessageHandler())
+            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: p2pGossipSync.asRoutingMessageHandler(), onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
         } else {
-            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: noCustomMessages.asRoutingMessageHandler(), onionMessageHandlerArg: noCustomMessages.asOnionMessageHandler(), customMessageHandlerArg: noCustomMessages.asCustomMessageHandler())
+            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: noRoutingMessages, onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
         }
         let timestampSeconds = UInt32(NSDate().timeIntervalSince1970)
@@ -226,12 +233,15 @@ public class ChannelManagerConstructor: NativeTypeWrapper {
         self.channelManager = ChannelManager(feeEst: params.feeEstimator, chainMonitor: params.chainMonitor.asWatch(), txBroadcaster: params.txBroadcaster, router: router, logger: params.logger, entropySource: params.entropySource, nodeSigner: params.nodeSigner, signerProvider: params.signerProvider, config: params.config, params: chainParameters, currentTimestamp: timestampSeconds)
         
-        let noCustomMessages = IgnoringMessageHandler()
+        let noCustomMessages = IgnoringMessageHandler().asCustomMessageHandler()
+        let noOnionMessages = IgnoringMessageHandler().asOnionMessageHandler()
+        let noRoutingMessages = IgnoringMessageHandler().asRoutingMessageHandler()
+
         var messageHandler: MessageHandler!
         if let netGraph = netGraph, params.enableP2PGossip {
             let p2pGossipSync = P2PGossipSync(networkGraph: netGraph, utxoLookup: nil, logger: params.logger)
             self.graphMessageHandler = GossipSync.initWithP2P(a: p2pGossipSync)
-            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: p2pGossipSync.asRoutingMessageHandler(), onionMessageHandlerArg: noCustomMessages.asOnionMessageHandler(), customMessageHandlerArg: noCustomMessages.asCustomMessageHandler())
+            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: p2pGossipSync.asRoutingMessageHandler(), onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
         } else {
-            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: noCustomMessages.asRoutingMessageHandler(), onionMessageHandlerArg: noCustomMessages.asOnionMessageHandler(), customMessageHandlerArg: noCustomMessages.asCustomMessageHandler())
+            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: noRoutingMessages, onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
         }
         
```

**Comment by tnull** [comment]
And some more cosmetics:

```diff
> git diff-tree -U2 03155f27 5aa79791
diff --git a/ci/LDKSwift/Sources/LDKSwift/batteries/ChannelManagerConstructor.swift b/ci/LDKSwift/Sources/LDKSwift/batteries/ChannelManagerConstructor.swift
index 224b6e36..0daa7229 100644
--- a/ci/LDKSwift/Sources/LDKSwift/batteries/ChannelManagerConstructor.swift
+++ b/ci/LDKSwift/Sources/LDKSwift/batteries/ChannelManagerConstructor.swift
@@ -187,4 +187,5 @@ public class ChannelManagerConstructor: NativeTypeWrapper {


+        let channelMessageHandler = channelManager.asChannelMessageHandler()
         let noCustomMessages = IgnoringMessageHandler().asCustomMessageHandler()
         let noOnionMessages = IgnoringMessageHandler().asOnionMessageHandler()
@@ -195,7 +196,7 @@ public class ChannelManagerConstructor: NativeTypeWrapper {
             let p2pGossipSync = P2PGossipSync(networkGraph: netGraph, utxoLookup: nil, logger: params.logger)
             self.graphMessageHandler = GossipSync.initWithP2P(a: p2pGossipSync)
-            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: p2pGossipSync.asRoutingMessageHandler(), onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
+            messageHandler = MessageHandler(chanHandlerArg: channelMessageHandler, routeHandlerArg: p2pGossipSync.asRoutingMessageHandler(), onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
         } else {
-            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: noRoutingMessages, onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
+            messageHandler = MessageHandler(chanHandlerArg: channelMessageHandler, routeHandlerArg: noRoutingMessages, onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
         }
         let timestampSeconds = UInt32(NSDate().timeIntervalSince1970)
@@ -233,4 +234,5 @@ public class ChannelManagerConstructor: NativeTypeWrapper {
         self.channelManager = ChannelManager(feeEst: params.feeEstimator, chainMonitor: params.chainMonitor.asWatch(), txBroadcaster: params.txBroadcaster, router: router, logger: params.logger, entropySource: params.entropySource, nodeSigner: params.nodeSigner, signerProvider: params.signerProvider, config: params.config, params: chainParameters, currentTimestamp: timestampSeconds)

+        let channelMessageHandler = channelManager.asChannelMessageHandler()
         let noCustomMessages = IgnoringMessageHandler().asCustomMessageHandler()
         let noOnionMessages = IgnoringMessageHandler().asOnionMessageHandler()
@@ -241,7 +243,7 @@ public class ChannelManagerConstructor: NativeTypeWrapper {
             let p2pGossipSync = P2PGossipSync(networkGraph: netGraph, utxoLookup: nil, logger: params.logger)
             self.graphMessageHandler = GossipSync.initWithP2P(a: p2pGossipSync)
-            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: p2pGossipSync.asRoutingMessageHandler(), onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
+            messageHandler = MessageHandler(chanHandlerArg: channelMessageHandler, routeHandlerArg: p2pGossipSync.asRoutingMessageHandler(), onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
         } else {
-            messageHandler = MessageHandler(chanHandlerArg: channelManager.asChannelMessageHandler(), routeHandlerArg: noRoutingMessages, onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
+            messageHandler = MessageHandler(chanHandlerArg: channelMessageHandler, routeHandlerArg: noRoutingMessages, onionMessageHandlerArg: noOnionMessages, customMessageHandlerArg: noCustomMessages)
         }
```

**Review by arik-so — APPROVED** [review]
lgtm

**Pull request merged**
